"""Document processing module for RAG analysis."""

import json
import pickle
import re
from pathlib import Path
from typing import List, Dict, Any, Optional
import logging

from langchain_community.document_loaders import PyPDFLoader, DirectoryLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
import pandas as pd
from app.rag_analysis.embedding_generator import EmbeddingGenerator
from app.config import Config
from app.database import db

logger = logging.getLogger(__name__)


class DocumentProcessor:
    """Handles document loading, splitting, and storage."""

    def __init__(self, data_directory: Optional[str] = None):
        """
        Initialize document processor.

        Args:
            data_directory: Directory containing PDF files
        """
        self.data_directory = Path(data_directory) if data_directory else Config.DATA_DIR / 'PDF Folder'
        logger.info(f" Data directory: {self.data_directory}")
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=Config.PDF_CHUNK_SIZE,
            chunk_overlap=Config.CHUNK_OVERLAP
        )
        self.embedding_generator = None

        if Config.PRE_LOAD_DATA:
            self.embedding_generator = EmbeddingGenerator()
            logger.info(f"Initialized embedding generator with model: {self.embedding_generator.model_name}")

    def _find_csv_analysis_pickle_path(self) -> Optional[Path]:
        """Find the CSV analysis pickle generated by CSVAnalyzer."""
        candidate_paths = [
            Config.OUTPUT_DIR / 'csv_analysis_results.pkl',
            Config.DATA_DIR / 'csv_analysis_results.pkl',
        ]

        for path in candidate_paths:
            if path.exists():
                return path

        logger.info("No csv_analysis_results.pkl file found in output or data directories")
        return None

    def _format_analysis_value(self, value: Any) -> str:
        """Convert analysis objects into readable text for embeddings."""
        if isinstance(value, pd.DataFrame):
            return value.to_string(index=False)

        if isinstance(value, pd.Series):
            return value.to_string()

        if isinstance(value, (dict, list, tuple)):
            return json.dumps(value, indent=2, default=str)

        return str(value)

    def _format_key_insights_for_search(self, insights: List[str]) -> str:
        """Format key insights into natural language text for better semantic search."""
        if not insights:
            return ""

        formatted = "Business Intelligence Insights:\n"
        for insight in insights:
            formatted += f"- {insight}\n"

        return formatted

    def _format_dimension_analysis_for_search(self, dimension_name: str, analysis: Dict) -> str:
        """Format dimension analysis into natural language text for better semantic search."""
        if not analysis:
            return ""

        formatted = f"Analysis by {dimension_name}:\n"

        for measure, categories in analysis.items():
            formatted += f"\n{measure} breakdown by {dimension_name}:\n"

            # Sort by total to show top performers first
            sorted_categories = sorted(
                categories.items(),
                key=lambda x: x[1].get('total', 0),
                reverse=True
            )

            for category, stats in sorted_categories[:5]:  # Top 5
                formatted += (
                    f"- {category}: Total ${stats['total']:,.2f}, "
                    f"Average ${stats['mean']:,.2f}, "
                    f"Count {stats['count']}\n"
                )

        return formatted

    def _load_csv_analysis_documents(self, pickle_path: Optional[Path] = None) -> List[Document]:
        """
        Load CSV analysis pickle results and convert them to LangChain documents.

        The CSV analyzer stores a dictionary of analysis sections. Creating one
        document per section gives vector search useful retrieval granularity.
        """
        pickle_path = pickle_path or self._find_csv_analysis_pickle_path()
        if not pickle_path:
            return []

        try:
            with pickle_path.open('rb') as f:
                analysis_results = pickle.load(f)
        except Exception as e:
            logger.warning(f"Failed to load CSV analysis pickle {pickle_path}: {e}")
            return []

        documents = []

        if isinstance(analysis_results, pd.DataFrame):
            for idx, row in analysis_results.iterrows():
                documents.append(Document(
                    page_content=f"CSV analysis row {idx}\n{row.to_string()}",
                    metadata={
                        'source': str(pickle_path),
                        'source_type': 'csv_analysis_pickle',
                        'file_name': pickle_path.name,
                        'type': 'csv_analysis',
                        'row_index': str(idx)
                    }
                ))
        elif isinstance(analysis_results, dict):
            for section_name, section_value in analysis_results.items():
                # Use special formatting for key insights and dimension analysis
                if section_name == 'key_insights' and isinstance(section_value, list):
                    section_text = self._format_key_insights_for_search(section_value)
                elif section_name == 'dimension_analysis' and isinstance(section_value, dict):
                    # Create separate documents for each dimension
                    for dimension_name, dimension_data in section_value.items():
                        dimension_text = self._format_dimension_analysis_for_search(dimension_name, dimension_data)
                        if dimension_text.strip():
                            documents.append(Document(
                                page_content=f"CSV analysis: {dimension_name} analysis\n{dimension_text}",
                                metadata={
                                    'source': str(pickle_path),
                                    'source_type': 'csv_analysis_pickle',
                                    'file_name': pickle_path.name,
                                    'type': 'csv_analysis',
                                    'analysis_section': f'dimension_analysis_{dimension_name}'
                                }
                            ))
                    continue
                else:
                    section_text = self._format_analysis_value(section_value)

                if not section_text.strip():
                    continue

                documents.append(Document(
                    page_content=f"CSV analysis section: {section_name}\n{section_text}",
                    metadata={
                        'source': str(pickle_path),
                        'file_name': pickle_path.name,
                        'source_type': 'csv_analysis_pickle',
                        'type': 'csv_analysis',
                        'analysis_section': section_name
                    }
                ))
        else:
            documents.append(Document(
                page_content=f"CSV analysis results\n{self._format_analysis_value(analysis_results)}",
                metadata={
                    'source': str(pickle_path),
                    'file_name': pickle_path.name,
                    'source_type': 'csv_analysis_pickle',
                    'type': 'csv_analysis'
                }
            ))

        logger.info(f"Loaded {len(documents)} CSV analysis documents from {pickle_path}")
        return documents

    def load_uploaded_documents(self, file_paths: List[str]) -> List[Document]:
        """Load user-uploaded PDF or pickle files into LangChain documents."""
        documents = []

        for file_path in file_paths:
            path = Path(file_path)
            suffix = path.suffix.lower()

            try:
                if suffix == ".pdf":
                    loaded = PyPDFLoader(str(path)).load()
                    for doc in loaded:
                        doc.metadata.update({
                            'source': str(path),
                            'file_name': path.name,
                            'source_type': 'uploaded_pdf',
                            'type': 'uploaded_document'
                        })
                    documents.extend(loaded)
                elif suffix in {".pkl", ".pickle"}:
                    documents.extend(self._load_csv_analysis_documents(path))
                else:
                    logger.warning(f"Unsupported upload type skipped: {path}")
            except Exception as e:
                logger.error(f"Failed to load uploaded file {path}: {e}")

        logger.info(f"Loaded {len(documents)} uploaded documents from {len(file_paths)} files")
        return documents

    def _store_documents_with_embeddings(self, documents: List[Document]) -> int:
        """Store preloaded LangChain documents and their chunks with embeddings."""
        if not documents:
            logger.warning("No documents found")
            return 0

        if self.embedding_generator is None:
            self.embedding_generator = EmbeddingGenerator()
            logger.info(f"Initialized embedding generator with model: {self.embedding_generator.model_name}")

        logger.info(f"Loaded {len(documents)} documents")

        texts = [doc.page_content for doc in documents]
        embeddings = self.embedding_generator.generate_embeddings(texts)
        logger.info(f"Generated embeddings for {len(documents)} documents")

        if len(embeddings) != len(documents):
            logger.error(
                f"Embedding count mismatch: {len(embeddings)} embeddings for {len(documents)} documents"
            )
            return 0

        if embeddings:
            logger.info(f"Embedding type: {type(embeddings[0])}")
            logger.info(f"First embedding length: {len(embeddings[0]) if isinstance(embeddings[0], list) else 'N/A'}")

        stored_documents = []
        for i, doc in enumerate(documents):
            metadata = self._make_json_safe({
                **doc.metadata,
                'source': doc.metadata.get('source', ''),
                'page': doc.metadata.get('page', 0),
                'total_pages': doc.metadata.get('total_pages', 0)
            })

            clean_content = doc.page_content.replace('\x00', '')

            document_id = db.store_embedding(clean_content, metadata, embeddings[i])
            if document_id:
                stored_documents.append((document_id, doc))
            else:
                logger.warning(f"Failed to store document {i}; skipping its chunks")

        stored_count = len(stored_documents)
        if stored_count == 0:
            logger.warning("No documents were stored")
            return 0

        chunks_with_document_ids = []
        for document_id, doc in stored_documents:
            doc_chunks = self.text_splitter.split_documents([doc])
            for chunk_index, chunk in enumerate(doc_chunks):
                chunks_with_document_ids.append((document_id, chunk_index, chunk))

        logger.info(f"Split {stored_count} stored documents into {len(chunks_with_document_ids)} chunks")
        if not chunks_with_document_ids:
            logger.warning("No chunks created")
            return stored_count

        chunk_texts = [chunk.page_content for _, _, chunk in chunks_with_document_ids]
        chunk_embeddings = self.embedding_generator.generate_embeddings(chunk_texts)
        logger.info(f"Generated embeddings for {len(chunks_with_document_ids)} chunks")

        if len(chunk_embeddings) != len(chunks_with_document_ids):
            logger.error(
                f"Chunk embedding count mismatch: {len(chunk_embeddings)} embeddings "
                f"for {len(chunks_with_document_ids)} chunks"
            )
            return stored_count

        chunks_data = []
        for i, (document_id, chunk_index, chunk) in enumerate(chunks_with_document_ids):
            chunks_data.append({
                'document_id': document_id,
                'chunk_text': chunk.page_content.replace('\x00', ''),
                'chunk_index': chunk_index,
                'embedding': chunk_embeddings[i]
            })

        stored_chunks = db.store_chunks_bulk(chunks_data)

        logger.info(f"Processed and stored {stored_count} documents and {stored_chunks} chunks with embeddings")
        return stored_count

    def process_uploaded_files(self, file_paths: List[str]) -> int:
        """Process uploaded PDF or pickle files and store them in the vector database."""
        documents = self.load_uploaded_documents(file_paths)
        return self._store_documents_with_embeddings(documents)

    def _make_json_safe(self, value: Any) -> Any:
        """Convert metadata values to JSON-serializable primitives."""
        if isinstance(value, dict):
            return {str(k): self._make_json_safe(v) for k, v in value.items()}

        if isinstance(value, (list, tuple, set)):
            return [self._make_json_safe(item) for item in value]

        try:
            json.dumps(value)
            return value
        except (TypeError, ValueError):
            return str(value)

    def load_documents(self, glob_pattern: str = "*.pdf") -> List[Document]:
        """
        Load documents from directory.

        Args:
            glob_pattern: Pattern to match files

        Returns:
            List of loaded documents
        """
        documents = []

        if self.data_directory.exists():
            logger.info(f"Loading documents from {self.data_directory}")
            try:
                loader = DirectoryLoader(
                    str(self.data_directory),
                    glob=glob_pattern,
                    loader_cls=PyPDFLoader,
                    recursive=True,
                    show_progress=True
                )
                documents = loader.load()
                logger.info(f"Loaded {len(documents)} PDF documents")
            except Exception as e:
                logger.error(f"Error loading PDF documents: {e}")
        else:
            logger.warning(f"Directory {self.data_directory} does not exist; skipping PDF loading")

        csv_documents = self._load_csv_analysis_documents()
        documents.extend(csv_documents)
        logger.info(f"Total documents after adding CSV analysis: {len(documents)}")

        return documents

    def split_documents(self, documents: List[Document]) -> List[Document]:
        """
        Split documents into chunks.

        Args:
            documents: List of documents to split

        Returns:
            List of document chunks
        """
        if not documents:
            logger.warning("No documents to split")
            return []

        logger.info(f"Splitting {len(documents)} documents into chunks")

        try:
            chunks = self.text_splitter.split_documents(documents)
            logger.info(f"Created {len(chunks)} chunks")
            return chunks

        except Exception as e:
            logger.error(f"Error splitting documents: {e}")
            return []

    def process_and_store_documents(self, glob_pattern: str = "*.pdf", force: bool = False) -> int:
        """
        Load, split, and store documents in database with embeddings.

        Args:
            glob_pattern: Pattern to match files

        Returns:
            Number of documents processed
        """
        # Check if data loading is enabled
        if not Config.PRE_LOAD_DATA and not force:
            logger.info("PRE_LOAD_DATA is set to False. Skipping PDF document processing.")
            return 0

        # Load documents
        logger.info(f"Loading documents from {self.data_directory} with pattern {glob_pattern}")
        documents = self.load_documents(glob_pattern)
        return self._store_documents_with_embeddings(documents)

    def reset_and_reload_documents(self, glob_pattern: str = "*.pdf") -> int:
        """Clear RAG documents and reload PDFs plus the CSV analysis pickle."""
        if not self.clear_database_documents():
            return 0

        return self.process_and_store_documents(glob_pattern=glob_pattern, force=True)

    def get_document_stats(self) -> Dict[str, Any]:
        """
        Get statistics about processed documents.

        Returns:
            Dictionary with document statistics
        """
        if not self.data_directory.exists():
            return {'error': 'Directory does not exist'}

        # Count PDF files
        pdf_files = list(self.data_directory.glob("*.pdf"))

        # Get database stats
        doc_count = db.execute_query("SELECT COUNT(*) as count FROM document_embeddings")
        chunk_count = db.execute_query("SELECT COUNT(*) as count FROM document_chunks")

        return {
            'directory': str(self.data_directory),
            'pdf_files_count': len(pdf_files),
            'pdf_files': [f.name for f in pdf_files],
            'stored_documents': doc_count[0]['count'] if doc_count else 0,
            'stored_chunks': chunk_count[0]['count'] if chunk_count else 0
        }

    def clear_database_documents(self) -> bool:
        """
        Clear all documents from database.

        Returns:
            True if successful, False otherwise
        """
        try:
            db.execute_query("TRUNCATE TABLE document_chunks, document_embeddings RESTART IDENTITY CASCADE")
            logger.info("Cleared all documents from database")
            return True
        except Exception as e:
            logger.error(f"Error clearing database: {e}")
            return False
